<?php
function download_block_block_info() {
    $block = array();
    $block['first_block'] = array(
        'info' => t('asdfasdfasdfdasf'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        'status' => TRUE,
    );
    return $block;
}

//function download_block_block_configure($delta = '') {
//    $form = array();
//    if ($delta == 'first_block') {
//        $form['block_example_string'] = array(
//            '#type' => 'textfield',
//            '#title' => t('block contents'),
//            '#size' => 60,
//            '#description' => t('test firs line block'),
//            '#default_value' => variable_get('block_example_string', t('some text')),
//        );
//    }
//    return $form;
//}
//
//function download_block_block_save($delta = '', $edit = array()) {
//    if ($delta == 'first_block') {
//        variable_set('block_example_string', $edit['block_example_string']);
//    }
//}
//
//function download_block_block_view($delta = '') {
//    $block = array();
//    switch($delta) {
//        case 'first_block':
//        $block['subject'] = t('Title of first block');
//        $block['content'] = download_block_contents($delta);
//        break;
//    }
//    return $block;
//}
//
//
//function download_block_contents($which_block) {
//    switch($which_block) {
//        case 'first_block':
//            $result = array(
//              '#markup' => variable_get('block_example_string', t('a default value')),
//            );
//            return $result;
//    };
//}
