<?php

/**
 * Implements hook_menu().
 */
function dwl_media_menu(){
    $items = array();

    $items['admin/config/media/dwl_media'] = array(
        'title' => 'Download media block',
        'description' => 'Configure download block media',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dwl_media_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

/**
 * Print dwl_media_main_form
 */
function dwl_media_form() {

    $form['block_title'] = array(
        '#title' => 'block title',
        '#description' => 'This title will display like block Title',
        '#type' => 'textfield',
    );

    $form['add_dw_media'] = array(
        '#type' => 'fieldset',
        '#title' => 'Add new Downloadable media',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
    );

    $form['add_dw_media']['name'] = array(
        '#type' => 'textfield',
        '#title' => 'link',
        '#description' => 'Download media link name',
    );

    $form['add_dw_media']['file'] = array(
        '#type' => 'managed_file',
        '#title' => 'File',
        '#description' => 'Choose file for users',
        '#upload_location' => 'public://files/'
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Save media',
    );

    return $form;

};

/**
 * validate media form
 */
function dwl_media_form_validate($form, &$form_state) {



};


function dwl_media_install() {
    if (!db_table_exists('dwl_media_table')) {
        $dwl_media_table_schema = array(
            'description' => 'User gained score by type, area and time.',
            'fields' => array(
                'dwl_media_title'	=> array('type' => 'varchar', 'length' => 256, 'not null' => TRUE, 'default' => ''),
                'dwl_media_name'    => array('type' => 'varchar', 'length' => 256, 'not null' => TRUE, 'default' => ''),
                'dwl_media_file'    => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
            ),
        );
    }
}

function dwl_media_install_schema($module) {
    $schema = drupal_get_schema_unprocessed($module);
    _drupal_schema_initialize($schema, $module, FALSE);

    foreach ($schema as $name => $table) {
        db_create_table($name, $table);
    }
}

/**
 * Submit media form
 */
function dwl_media_form_submit($form, &$form_state) {
    dsm($form_state);
    db_insert('dwl_media_table')
        ->fields(array(
            'dwl_media_title'   => $form_state['values']['block_title'],
            'dwl_media_name'    => $form_state['values']['name'],
            'dwl_media_file'    => $form_state['complete form']['add_dw_media']['file']['fid']['#value'],
        ))->execute();


    $block_title = $form_state['values']['block_title'];
    drupal_set_message( t('Thanks for filling out the form, %block_title', array('%block_title' => $block_title)) );
}
